urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url, static
from django.views.generic import TemplateView, RedirectView
#from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

#from ssl_authenticate.views import login
#from gridbox import dm

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'temp.views.home', name='home'),
    # url(r'^temp/', include('temp.foo.urls')),

    #send root url to login
    url(r'^$', 'ssl_authenticate.views.certificate_login', name='index'),
    #TemplateView.as_view(template_name='index.html'), name="home"),

    url(r'^contact/', TemplateView.as_view(template_name='base/contact.html'), name="contact"),
    url(r'^about/', TemplateView.as_view(template_name='base/about.html'), name="about"),
    url(r'^howto/', TemplateView.as_view(template_name='base/howto.html'), name="howto"),
    # Uncomment the admin/doc line below to enable admin documentation:

    # admin urls
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^reset/', 'filestorage.reset.reset'),
    #user authentication urls
    #url(r'^accounts/auth/$', 'testing.views.auth_view'),
    url(r'^accounts/certlogin/$', 'ssl_authenticate.views.certificate_login', name="certlogin"),
    url(r'^accounts/simplelogin/$', 'ssl_authenticate.views.simple_login', name="simplelogin"),
    url(r'^accounts/logout/$', 'ssl_authenticate.views.logout', name="logout"),
    url(r'^accounts/loggedin/$', 'ssl_authenticate.views.logged_in', name="loggedin"),
    url(r'^accounts/invalid/$', 'ssl_authenticate.views.invalid_login', name="invalid"),
    url(r'^accounts/profile/$', 'ssl_authenticate.views.profile', name="profile"),

    # registration of new users
    url(r'^accounts/register/$', 'ssl_authenticate.views.register_user', name='register'),
    url(r'^accounts/register_success/$', 'ssl_authenticate.views.register_success', name='registersuccess'),

    # data manipulation urls
    #url(r'^data/$', 'filestorage.views.alldata'),
    url(r'^data/all/$', 'filestorage.views.alldata', name="viewalldata"),
    url(r'^data/groupall/$', 'filestorage.views.group_data', name="viewgroupdata"),
    url(r'^data/create/$', 'filestorage.views.create', name="datacreate"),
    url(r'^data/choose/$', 'filestorage.views.choose_data', name="choose_data"),
    url(r'^data/edit/(\d+)/$', 'filestorage.views.edit_data', name="edit_data"),
    url(r'^data/incomplete/$', 'filestorage.views.incomplete_data', name="nofile"),
    url(r'^data/fileupload/$', 'filestorage.views.reserve_fileupload_space', name="fileupload"),
    url(r'^data/download/$', 'filestorage.views.file_download', name="download"),
    url(r'^data/upload/$', 'filestorage.views.file_upload', name="upload"),
    url(r'^data/segment_upload/$', 'filestorage.views.file_segment_upload', name="segment_upload"),
    url(r'^data/get/(?P<data_id>\d+)/$', 'filestorage.views.data_display', name="datadisplay"),
    url(r'^data/success/$', 'filestorage.views.upload_success', name="upload_success"),
)

urlpatterns += static.static('/browse/', document_root=settings.UPLOAD_DIRECTORY)

filestorage/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User, Group
from celery.worker.strategy import default

class StoredFileMetadata(models.Model):

    title = models.CharField(max_length=150)
    description = models.TextField(max_length=750)
    subject = models.CharField(max_length=25)
    publisher = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=20)
    format = models.CharField(max_length=20)
    identifier = models.CharField(max_length=20)
    source = models.CharField(max_length=20)
    language = models.CharField(max_length=10)
    relation = models.CharField(max_length=20)
    coverage = models.CharField(max_length=20)
    rights = models.CharField(max_length=20)

    creator = models.ForeignKey(User)
    #file = models.OneToOneField('FileStorageParameters', blank=False)

    class Meta: # default sorting order when data retrieved
        ordering = ['title']

    def __unicode__(self):
        return str(self.title)

class FileStorageParameters(models.Model):

    filemetadata = models.OneToOneField(StoredFileMetadata)
    filename = models.CharField(max_length=255)
    se_base_path = models.ManyToManyField('StorageElementBasePath', through='FilesSE')
    file_vo = models.ManyToManyField('VirtualOrganisation', through='FileVO')
    file_group = models.ForeignKey(Group)
    file_successfully_moved_to_se = models.BooleanField(default=False)
    file_successfully_uploaded_to_staging = models.BooleanField(default=False)

    def __unicode__(self):
        return str(self.filename)

#     @staticmethod
#     def get_users_groups():
#         return Group.objects.all().filter(user__username=user)

class FilesSE(models.Model):

    '''Linker table to connect Storage Element information with File Information'''

    file_info = models.ForeignKey(FileStorageParameters)
    se_info = models.ForeignKey('StorageElementBasePath')

class StorageElementBasePath(models.Model):

    #filename = models.ManyToManyField('FileStorageParameters', through='FilesSE')
    location = models.CharField(max_length=50)
    storage_element = models.CharField(max_length=255)
    base_path = models.CharField(max_length=255)

    def __unicode__(self):
        return str(self.storage_element)

class FileVO(models.Model):

    ''' Linker table to connect the File Information with the Virtual Organisation '''

    file_info = models.ForeignKey(FileStorageParameters)
    vo_info = models.ForeignKey('VirtualOrganisation')

    def __unicode__(self):
        return str(self.file_info)


class VirtualOrganisation(models.Model):

    virtual_organisation = models.CharField(max_length=255)
    user_id = models.ManyToManyField(User, through='UserVO')

    def __unicode__(self):
        return str(self.virtual_organisation)

class UserVO(models.Model):

    ''' Linker table to connect the Virtual Organisation with the User Profile '''

    username = models.ForeignKey(User)
    virtual_organisation = models.ForeignKey(VirtualOrganisation)

    def __unicode__(self):
        return str(self.virtual_organisation)


class ActiveGridInteractions(models.Model):

    timestamp = models.DateTimeField(auto_now_add=True)
    tcp_address = models.CharField(max_length=255)
    grid_interaction = models.CharField(max_length=255)
    grid_id = models.CharField(max_length=255)
    robot_certificate = models.CharField(max_length=255)
    proxy_id = models.CharField(max_length=255)
    virtual_organisation = models.CharField(max_length=255)
    fqan = models.CharField(max_length=255)
    user_description = models.CharField(max_length=255)
    status = models.CharField(max_length=255)
    grid_ce = models.CharField(max_length=255)
    latitude = models.CharField(max_length=255)
    longitude = models.CharField(max_length=255)
    timestamp_endjob = models.CharField(max_length=255)

#     def __unicode__(self): #(return the relevant unicode string)
#         return self.guid

class CompletedGridInteractions(models.Model):

    guid = models.CharField(max_length=38)

    def __unicode__(self): #(return the relevant unicode string)
        return self.guid


admin.site.register(StoredFileMetadata)
admin.site.register(StorageElementBasePath)
admin.site.register(FilesSE)
admin.site.register(FileStorageParameters)
admin.site.register(FileVO)
admin.site.register(VirtualOrganisation)
admin.site.register(UserVO)
admin.site.register(CompletedGridInteractions)

filestorage/views.py
from django.conf import settings
import os

from django.contrib.auth.decorators import login_required
from django.contrib.auth import models
from django.contrib.auth.models import User, Group
from django.db.models import Q

from django.core.urlresolvers import reverse
from django.core.validators import URLValidator
from django.core.exceptions import (ValidationError, ObjectDoesNotExist)
from django.core.paginator import (Paginator, EmptyPage, PageNotAnInteger)
from django.core.files.uploadhandler import (FileUploadHandler, UploadFileException)

import requests
from django.shortcuts import *

from django.http import HttpResponse, HttpResponseRedirect
from django.template.response import TemplateResponse
import json

from celery import Celery
from settings.celery import app


from django import forms
from filestorage.forms import StoredFileMetadataForm, FileForm, UploadFileForm
from models import StorageElementBasePath, FileStorageParameters, VirtualOrganisation, FilesSE, FileVO, StoredFileMetadata


from lfcinteract.tasks import copy_file
from proxy.tasks import check_proxy_health


from django.core.context_processors import csrf
import logging
from django.http.response import HttpResponseServerError

@login_required
def alldata(request):

    '''
    Need to make this viewing only by superuser
    '''

    return render(request, 'filestorage/alldata.html',
                  {'data' : StoredFileMetadata.objects.all()})

@login_required
def incomplete_data(request):

    '''
    For when datasets are saved but there is no SE base path specified
    '''

    logger = logging.getLogger(__name__)
    args = {}

    #args['data'] = FileStorageParameters.objects.filter(se_base_path__isnull=True).select_related('filemetadata').prefetch_related('se_base_path', 'file_vo')
    args['data'] = StoredFileMetadata.objects.filter(Q(filestorageparameters__isnull=True) | Q(filestorageparameters__file_successfully_uploaded_to_staging=False)).select_related('filemetadata')


    logger.info("# of incomplete datasets...{0}".format(len(args['data'])))
    logger.info(args['data'].values())

    if len(args['data']) <= 25:
        paginator = Paginator(args['data'], len(args['data']))
    else:
        paginator = Paginator(args['data'], 25) # Show 25 datasets per page

    logger.info("loading {0} datasets into paginator".format(len(args['data'])))

    page = request.GET.get('page')

    try:
        datasets = paginator.page(page)
    except PageNotAnInteger, e:
        logger.error("Exception = {0}".format(e))
        try:
            datasets = paginator.page(1)
        # If page is not an integer, deliver first page.
        #datasets = paginator.page(1)
        except ZeroDivisionError:
            paginator.page(0)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        logger.error("Exception = {0}".format(e))
        datasets = paginator.page(paginator.num_pages)

    logger.info("number of datasets in Queryset...{0}".format(len(args['data'])))

    return render(request, 'filestorage/incomplete.html', {"datasets" : datasets})

@login_required
def choose_data(request):
    logger = logging.getLogger(__name__)

    if request.method == 'GET':
        try:
            selected_pk = request.GET.getlist("selectdata")
            logger.info("user selected dataset...{0}".format(selected_pk[0]))
            url = reverse('datadisplay', args=[selected_pk[0]])
        except IndexError:
            url = Http404

    return HttpResponseRedirect(url)

@login_required
def edit_data(request, dataset):
    logger = logging.getLogger(__name__)

    try:
        selected_metadata = StoredFileMetadata.objects.get(pk=dataset)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('fileupload'))

    logger.info("dataset {0} is...{1}".format(dataset, selected_metadata))

    form = StoredFileMetadataForm(instance=selected_metadata)
    logger.info("instantiating metadata form with bound data")

    if request.method == 'POST':
        if form.is_valid():
            logger.info("metadata form is valid")
            data = form.save(commit=False)
            data.creator = request.user

            #logger.info("metadata pk made available - %s", data.pk)
            data.save()

            logger.info("fields in data form instance...{0}".format(data.pk))
            request.session['metapk'] = data.pk

            #url = reverse('fileupload')
            #logger.info('fileupload reverse URL = %s', url)
            #return HttpResponseRedirect(url)

    args = {}
    args.update(csrf(request))

    args['form'] = form

        #url = reverse('datacreate')
        #logger.info('reversing name URL "datacreate" - %s', url)

    return render(request, 'filestorage/editdata.html', args)

@login_required
def group_data(request):

    '''
    User only views data they have created or have access to by Group.
    '''

    logger = logging.getLogger(__name__)

    args = {}
    args['data'] = FileStorageParameters.objects.all().select_related('filemetadata').prefetch_related('se_base_path', 'file_vo')

    paginator = Paginator(args['data'], 25) # Show 25 datasets per page

    logger.info("loading 25 datasets into paginator...{0}".format(paginator))

    page = request.GET.get('page')
    try:
        datasets = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        datasets = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        datasets = paginator.page(paginator.num_pages)

    logger.info("number of datasets in Queryset...{0}".format(len(args['data'])))

    return render(request,'filestorage/alldata.html', {"datasets": datasets})

@login_required
def data_display(request, data_id):

    '''
    User only views data they have created or have access to by Group.
    '''
    logger = logging.getLogger(__name__)
    logger.info("selected data record #...{0}".format(data_id))
    args={}
    try:
        # need to forward to file upload url
        args['data'] = FileStorageParameters.objects.get(pk=data_id)

        #.select_related('filemetadata').prefetch_related('se_base_path', 'file_vo')
    except ObjectDoesNotExist:
        logger.error('dataset incomplete - capturing file upload options')
        request.session['metapk'] = data_id
        url = reverse('fileupload')
        return HttpResponseRedirect(url)

    return render(request, 'filestorage/data.html', {'data': args['data']})


#     logger = logging.getLogger(__name__)
#     language = 'en-gb'
#     session_language = 'en-gb'
#
#     if 'lang' in request.COOKIES:
#         language = request.COOKIES['lang']
#
#     if 'lang' in request.session:
#         session_language = request.session['lang']
#
#     args = {}
#     args.update(csrf(request))
#
#     args['data'] = CurrentData.objects.all()
#     args['language'] = language
#     args['session_language'] = session_language
#     logger.debug(args['data'])
#     return render_to_response('data.html', {'datalist' : args})


@login_required
def create(request):

    logger = logging.getLogger(__name__)
    form = StoredFileMetadataForm(request.POST or None)

    if request.POST:
        if form.is_valid():
            logger.info("metadata form is valid")

            data = form.save(commit=False)

            data.creator = request.user

            #logger.info("metadata pk made available - %s", data.pk)
            data.save()

            logger.info("fields in data form instance..{0}".format(data.pk))
            request.session['metapk'] = data.pk

            url = reverse('fileupload')
            logger.info('fileupload reverse URL = {0}'.format(url))
            return HttpResponseRedirect(url)
        #('/witsdata4grid/data/fileupload/')
    #else:
    #    form = StoredFileMetadataForm(request.POST or None)
            #return HttpResponseRedirect(reverse('fileupload'))

    args = {}
    args.update(csrf(request))

    args['form'] = form

    url = reverse('datacreate')
    logger.info('reversing name URL "datacreate"...{0}'.format(url))

    return render(request, 'filestorage/create_newdata.html', args)

# @login_required
# def gridbox_request(request_url):
#
#     logger = logging.getLogger(__name__)
#
#     logger.info("Gridbox Server URL...%s",settings.GRIDBOX_URL)
#
#     #headers = {'x-auth-ip' : '146.141.177.54'}
#     #params = {'authip' : '146.141.177.54'}
#     book_upload_space = requests.get(settings.GRIDBOX_URL + request_url, params=params, headers=headers)
#     #book_upload_space = requests.put('127.0.0.1/webdav' + request_url)
#     logger.info("Gridbox fields...%s", dir(book_upload_space))
#     logger.info("Gridbox redirect url...%s", book_upload_space.url)
#
#     logger.info("Gridbox status code...%s", book_upload_space.status_code)
#
#     return book_upload_space

#@login_required
def reserve_fileupload_space(request):
#(request, *args, **kwargs):
    '''


    URL must be configured as follows "/upload/<vo>/<filename>/<se>/<path:path>"
    '''

    logger = logging.getLogger(__name__)

    virtual_organisation = get_vo_choices(request.user)
    project = get_group_choices(request.user)
    location = get_location_choices()

    form = FileForm(request.POST, virtual_organisation=virtual_organisation, location=location, project=project)

    if request.POST:
        logger.info('request.POST form dir...{0}'.format(request.POST))
        if form.is_valid():
            new_file = form.save(commit=False)

            logger.info("filename...{0}".format(form.cleaned_data['filename']))
            logger.info("se_base_path...{0}".format(form.cleaned_data['se_base_path']))
            logger.info("file_vo...{0}".format(form.cleaned_data['file_vo']))
            logger.info("project...{0}".format(form.cleaned_data['project']))

            stored_metadata = request.session['metapk']

templates/filestorage/alldata.html
{% extends "base/base.html" %}

{% block body_block %}

{% block page_header %}<h4>Data you have access to</h4>{% endblock page_header %}

{% block paginate %}
<div class="pagination">
    <span class="step-links">
        {% if datasets.has_previous %}
            <a href="?page={{ datasets.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ datasets.number }} of {{ datasets.paginator.num_pages }}.
        </span>

        {% if datasets.has_next %}
            <a href="?page={{ datasets.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% endblock paginate %}

{% block table_headers %}
<div class="container">
    <table style="width:80%" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Created</th>
            <th>Title</th>
            <th>Subject</th>
            <th>Filename</th>
            <th>Stored At</th>
            <th>VO</th>
            <th>Project</th>
            <th>Select</th>
        </tr>
    </thead>
{% endblock table_headers %}

{% block tablebody %}

    <form action="{% url 'choose_data' %}" method="get">

    {% for items in datasets %}
      {% for elements in items.se_base_path.all %}
        {% if elements.location|length != 0 %}
            <tr>
                <td>{{items.filemetadata.created_at|date:"d M Y"}}</td>
                <td>{{items.filemetadata.title}}</td>
                <td>{{items.filemetadata.subject}}</td>
                <td>{{items.filename}}</td>
                <td>{{elements.location}}</td>
                {% for vos in items.file_vo.all %}
                    <td>{{vos.virtual_organisation}}</td>
                {% endfor %}
                <td>{{ items.file_group }}</td>
                <td>
                    <label class="radio inline"><input type="radio" name="selectdata" value="{{items.filemetadata.pk}}" /></label>
                </td>
            </tr>
        {% endif %}
      {% endfor %}
    {% endfor %}
{% endblock tablebody %}
    <input type="submit" value="Select Dataset" method="get"/><br />
    </form>
</table>
</div>

{% endblock body_block %}

{% block data_access %}

            <a href="{% url 'datacreate' %}" class="btn btn-primary">Download Data </a>
            <a href="{% url 'nofile' %}" class="btn btn-primary">Share Data</a>

{% endblock data_access %}

templates/filestorage/create_newdata.html
{% extends "base/base.html" %}
{% load i18n %}

{% block body_block %}
  <div class="page-header">
    <h5>Please enter the metadata that will be associated with your uploaded data.</h5>
    </div>
<div class="span10">
<form role=form class='form-inline' action="{% url 'datacreate' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
     <div class="controls controls-row">
        <label for="title"> Title </label> <br />
        <input type="text" id="id_title" name="title" placeholder="Enter data title"> <br/>

        <label for="title">Description</label><br />
        <textarea rows="5" id="id_description" name="description" placeholder="Enter a good description of the data"></textarea><br />

        <hr />

        <label for="title">Subject</label>
        <input type="text" class="form-control" id="{{form.subject.id}}" name="subject" placeholder="Subject">
        <label for="title">Publisher</label>
        <input type="text" class="form-control" id="id_publisher" name="publisher" placeholder="Publisher">

        <label for="title">Type</label><br />
        <input type="text" id="id_type" name="type" placeholder="Type"> <br/>
        <label for="title">Publisher</label><br />
        <input type="text" id="id_format" name="format" placeholder="Format"> <br/>

        <label for="title">Identifier</label><br />
        <input type="text" id="id_identifier" name="identifier" placeholder="Identifier"> <br/>
        <label for="title">Source</label><br />
        <input type="text" id="id_source" name="source" placeholder="Source"> <br/>

        <label for="title">Language</label><br />
        <input type="text" class="form-control" id="id_language" name="language" placeholder="Language"> <br/>
        <label for="title">Relation</label><br />
        <input type="text" class="form-control" id="id_relation" name="relation" placeholder="Relation"> <br/>

        <label for="title">Coverage</label><br />
        <input type="text" class="form-control" id="id_coverage" name="coverage" placeholder="Coverage"> <br/>
        <label for="title">Rights</label><br />
        <input type="text" class="form-control" id="id_rights" name="rights" placeholder="Rights"> <br/>
        <button type="submit" id="submit" name=submit class="btn btn-primary" value="Save Metadata" method=post>Submit</button>
    </div>

    </div>
    <br/>



</form>
</div>

{% endblock %}

{% for field in form.visible_fields %}
    <div class="control-group {{ field.html_name }} {% if field.errors %}error{% endif %}">
        <label class="control-label">{{ field.label }}{% if field.field.required %} *{% endif %}</label>
        <div class="controls">
            {{ field }}
            {% if field.errors %}<span class="help-inline">{{ field.errors.as_text }}</span>{% endif %}
        </div>
    </div>
{% endfor %}


<input type="submit" name="submit" value="Save Metadata" method="post"/>

<script src="{% static 'js/filestorage.js' %}"></script>

templates/filestorage/data.html
{% extends "filestorage/alldata.html" %}
{% load i18n %}

{% block paginate %}
{% endblock paginate %}

{% block page_header %}<h4>Data - {{data.filemetadata.title}}</h4>{% endblock page_header %}

{% block tablebody %}

        {{ items.filemetadata.title }}
        <tr>
            <td>{{ data.filemetadata.created_at}}</td>
            <td>{{ data.filemetadata.title}}</td>            
            <td>{{ data.filemetadata.subject}}</td>
            <td>{{ data.filemetadata.publisher}}</td>           
            <td>{{ data.filemetadata.type}}</td>
            <td>{{ data.filemetadata.format}}</td>
            <td>{{ data.filemetadata.identifier}}</td>
            <td>{{ data.filemetadata.source}}</td>
            <td>{{ data.filemetadata.language}}</td>
            <td>{{ data.filemetadata.relation}}</td>
            <td>{{ data.filemetadata.coverage}}</td>
            <td>{{ data.filemetadata.rights}}</td>            
        </tr>
        <tr>
            <td>{{ data.filemetadata.description}}</td>
        </tr>
        
   <thead>
       <tr>
           <th>Filename</th>
           <th>Location</th>
           <th>VO</th>
           <th>Group</th>            
       </tr>
   </thead>
       <tr>   
           <td>{{data.filename}}</td>               
           <td>{{data.se_base_path.get}}</td>               
           <td>{{data.file_vo.get}}</td>
           <td>{{data.file_group}}</td>   
       </tr>
{% endblock tablebody %}
        

    

templates/filestorage/download.html
{% extends "filestorage/alldata.html" %}
{% load i18n %}

{% block sidenav %}
<div class="container-fluid">
<div class="row-fluid">
    <div class="span2">
        <div class="sidebar-nav">
            <a href="{% url 'datacreate' %}" class="btn btn-primary">Enter Data </a>
            <!-- <a href="{% url 'fileupload' %}" class="btn btn-primary">Upload File</a> -->
            <a href="{% url 'nofile' %}" class="btn btn-primary">Fix Upload</a>
            
        </div>
    </div>
{% endblock sidenav %}

<div class="container">
    <table style="width:80%" class="table table-striped table-bordered">
    
    {% block table_headers %}
    <thead>
        <tr>
            <th>Created</th>
            <th>Filename</th>
            <th>Title</th>
            <th>Stored At</th>
            <th>VO</th>
            <th>Project</th>
            <th>Select</th>
        </tr>
    </thead>
{% endblock table_headers %} 
    
{% block tablebody %}
<tbody>
<form action="{% url 'choose_data' %}" method="get">

    {% for items in datasets %}
      {% for elements in items.se_base_path.all %}
        
            <tr>
                
                <td>{{items.filemetadata.created_at|date:"d M Y"}}</td>
                <td>{{items.filename}}</td>
                <td>{{items.filemetadata.title}}</td>                
                
                <td>{{elements.location}}</td>
                
                {% for vos in items.file_vo.all %}
                    <td>{{vos.virtual_organisation}}</td>
                {% endfor %}
                
                <td>{{ items.file_group }}</td>
                <td><label class="radio inline"><input type="radio" name="selectdata" value="{{items.pk}}" /></label></td>                                   
            </tr>
      {% endfor %}
    {% endfor %}
<input type="submit" value="Download File" method="get"/><br />    
</form>
</tbody />
{% endblock tablebody %}
    </table>
</div>

templates/filestorage/incomplete.html
{% extends "filestorage/alldata.html" %}

    {% block page_header %}<h4>Datasets that are incomplete</h4>{% endblock page_header %}

{% block table_headers %}
<div class="container">
    <table style="width:80%" class="table table-striped table-bordered">
     <tr>
    <th>Select</th>
    <th>Created</th>
    <th>Title</th>
    <th>Subject</th>
    <th>Publisher</th>
    <th>Type</th>
    <th>Format</th>
    <th>Identifier</th>
    <th>Source</th>
    <th>Language</th>
    <th>Relation</th>
    <th>Coverage</th>
    <th>Rights</th>
  </tr>
    {% endblock table_headers %}
    {% block tablebody %}
<tr>
        <form action="{% url 'choose_data' %}" method="get">
        {% for items in datasets %}
            <td><label class="radio inline"><input type="radio" name="selectdata" value="{{items.pk}}" /></label></td>
            <td>{{ items.created_at}}</td>
            <td>{{ items.title}}</td>
            <td>{{ items.subject}}</td>
            <td>{{ items.publisher}}</td>
            <td>{{ items.type}}</td>
            <td>{{ items.format}}</td>
            <td>{{ items.identifier}}</td>
            <td>{{ items.source}}</td>
            <td>{{ items.language}}</td>
            <td>{{ items.relation}}</td>
            <td>{{ items.coverage}}</td>
            <td>{{ items.rights}}</td>
  </tr>
  <tr>
    <td></td>
    <th>Description<br></th>
    <td colspan="11">{{ items.description}}</td>
  </tr>
    </thead>

    {% endfor %}
    {% endblock tablebody %}



        {{items.title}}
        <tr>

        </tr>
        <tr>
            <th>{{ items.description}}</th>
            </tr>

templates/filestorage/metadata.html
{% extends "base/base.html" %}

templates/filestorage/reserve_upload_space.html
{% extends "base/base.html" %}
{% load i18n %}

{% block body_block %}
<div class="hero-unit">

This is supposed reserve a filename space on the DPM server.


{% if user.is_authenticated %}
	<form action="{% url 'fileupload' %}" method="post" enctype="multipart/form-data">{% csrf_token %}

		 <ul>
            {{form.as_ul}}
        </ul>
        <input type="submit" name="submit" id="submitFile" value="Check Upload" method="post"/>
	</form>
{% endif %}

{# can change action to a URL #}
{# /upload/<vo>/<filename>/<se>/<path:path> #}
{# /download/<vo>/<se>/<path:path> #}

vo is from FileStorageParameters (drop down menu) <br>
se is from Institution (drop down menu) <br>
path:path is from se and group/project (drop down menu) <br>
filename is appended to the end of path <br><br>


{# user = models.ForeignKey(User) #}
{# filename = models.CharField(max_length=255) #}
{# filepath = models.CharField(max_length=255)  #}
{# project = models.CharField(max_length=255)  #}
{# virtual_organisation = models.CharField(max_length=255)  #}
{# institution = models.CharField(max_length=255) #}


{#<form id="file-form" action="handler.php" method="POST">#}
{#  <input type="file" id="file-select" name="photos[]" />#}
{#  <button type="submit" id="upload-button">Upload</button>#}
{#</form>#}


</div>

{% endblock %}

<script src='https://code.jquery.com/jquery-2.1.0.min.js'></script>
<script src="{% static 'js/filestorage.js' %}"></script>

templates/filestorage/success.html
Thanks, file has been uploaded